# Generated by Django 4.0.1 on 2022-02-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('DesignationId', models.AutoField(primary_key=True, serialize=False)),
                ('DesignationTitle', models.CharField(max_length=500)),
            ],
        ),
    ]
